[package]
name = "micro-repeat"
version = "0.1.0"
authors = ["Nicholas Sim <nicholassimws@gmail.com>"]

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
opt-level = 0
