[package]
name = "heapsort"
version = "0.1.0"
authors = ["Nicholas Sim <nicholassimws@gmail.com>"]
edition = "2018"

[dependencies]
libc = { git = "https://github.com/nw0/rust-crate-libc.git", branch = "cheri-47" }

[profile.release]
panic = "abort"
